name: Git-checkouter

# Trigger which git action (push, pull_request)
# in which branch(es) should start the jobs...
on:
  workflow_run:
    workflows: ["Test"]
    branches: ["main"]
    types:
      - completed
# jobs to run
jobs:
  # build, the name of the job, a server to create and auto configure
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Checkout main to web server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ls
      #with: 
      #  path: main
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: '*.*'
        target: /var/www/html